sudo: required
services:
  - docker

before_install:
  - docker build -t bappa0604/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bappa0604/docker-react npm run test -- --coverage
